Module 1: Portfolio desktop version
amare1990/Portfolio-Amare pull request #1
Opened 2022-08-31 22:16 UTC by amare1990

- Used media queries for the desktop version of the Portfolio project.
- Optimize to reuse markup components again.
- Use Figma to collect fonts, margins, colors and arrangements and develop the project.
- Use mini-width screen attribute for the desktop version
- Use max-width to not display the desktop version components.
- Use **display: none;** css rule to not display the desktop version when the screen size is below 768px,

2022-08-31 23:13 UTC, tufoinnkuo10 requested changes
Hi @amare1990 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅media query well used 

# Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +<body>
- [ ] please kindly remove the red background appearing on the mobile version. also the hamburger menu has disappeared. please fix that
- [ ] kindly remove the left margin and the red background color from it.
![Screenshot (378)](https://user-images.githubusercontent.com/65298048/187798667-4d2cdf06-2904-435c-912e-ae488cfacc88.png)
![Screenshot (379)](https://user-images.githubusercontent.com/65298048/187798704-3849d125-9036-49f4-842b-aa878b810e24.png)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +        <span class="contact-me-title">Contact me</span>
- [ ] text and input fields in the mobile section are overflowing .. please fix that.
![Screenshot (381)](https://user-images.githubusercontent.com/65298048/187798885-ab9a37ed-1b56-42e0-9c84-21a21dfed9d9.png)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +<body>
- [ ] please there is this extra margin surrounding your profile. kindly fix that
- [ ] also ensure that your text and contents are centralized on the page
your design
![Screenshot (383)](https://user-images.githubusercontent.com/65298048/187799229-9db4740f-914e-4d80-941f-23da7b535b2c.png)
figma
![Screenshot (385)](https://user-images.githubusercontent.com/65298048/187799567-bef390cc-6c3c-49c8-ac40-5800ad4dea0e.png)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +        <ul class="menu-desk">
- [ ] your cards are aligned to the left in the desktop version. please fix that.
![Screenshot (387)_LI](https://user-images.githubusercontent.com/65298048/187799801-f7053315-6e06-47bf-862e-cea0218e3ecd.jpg)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +          </li>
- [ ] please remove this extra margin on the right.
![Screenshot (389)_LI](https://user-images.githubusercontent.com/65298048/187799966-6b397b1b-96ac-4758-8977-e33e19ea4ec1.jpg)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +               About <br> Myself
- [ ] please fix the about me section so i looks like the figma design.

your design
![Screenshot (392)_LI](https://user-images.githubusercontent.com/65298048/187800289-ab454882-7184-4d8c-9513-671be83ce2f3.jpg)
figma design

![Screenshot (393)](https://user-images.githubusercontent.com/65298048/187800371-36ea9f2a-5441-4e0b-bdfa-311234b3109e.png)
![Screenshot (393)](https://user-images.githubusercontent.com/65298048/187800660-223c69e6-c25b-40a2-a3f5-1db05ba12bf1.png)

2022-08-31 23:13 UTC, tufoinnkuo10 commented on index.html
> +      <div class="form-container">
- [ ] please ensure that the desktop version contact section is centralize like the figma version.

2022-09-01 23:26 UTC, cynthiainga requested changes
Hi @amare1990, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Use correct Github flow ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 23:26 UTC, cynthiainga commented on index.html
> +    </footer>
- [ ] I think it would be better if your design stick as much as possible to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) as mention in the project requirements and as mentioned by the previous reviewer, you need to center this section and also fix the background image 🙃 🙃 

Your design
<img width="927" alt="Screen Shot 2022-09-02 at 00 48 17" src="https://user-images.githubusercontent.com/74501523/188025973-0546ee2a-df3d-4f40-ac57-686cb3097768.png">

Figma design
<img width="868" alt="Screen Shot 2022-09-02 at 00 48 57" src="https://user-images.githubusercontent.com/74501523/188026009-46eccf8e-1897-4e8d-aa09-26eb3232abbc.png">

2022-09-01 23:26 UTC, cynthiainga commented on index.html
> +    <section id="about" class="section-about-myself background-color">
- [ ] Please as mentioned by the previous reviewer, your design of this section should stick as much as possible to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1), e.g., font, colors, images, text, margins,... 🙃 🙃 
You can see the difference between your design and Figma's design

Your design
<img width="935" alt="Screen Shot 2022-09-02 at 00 46 00" src="https://user-images.githubusercontent.com/74501523/188026614-b5f56944-88b2-46ca-89b7-cda60fe9e9dc.png">

Figma design
<img width="864" alt="Screen Shot 2022-09-02 at 00 46 32" src="https://user-images.githubusercontent.com/74501523/188026645-d89031c2-b788-42f2-9df1-a86a4147570e.png">

2022-09-01 23:26 UTC, cynthiainga commented on index.html
> +          </ul>
- [OPTIONAL] Please kindly make sure your list of technologies and the title are styled correctly, take a look at the pictures below 🙃 

Your design
<img width="910" alt="Screen Shot 2022-09-02 at 00 43 02" src="https://user-images.githubusercontent.com/74501523/188027586-0555cbc3-45ec-4b67-9091-eb1e7a2ff5b3.png">

Figma design
<img width="873" alt="Screen Shot 2022-09-02 at 00 44 20" src="https://user-images.githubusercontent.com/74501523/188027646-265aa7fc-8c1e-4220-b6a5-c84ff1fc3138.png">

- [OPTIONAL] Also make sure that your images are clear so that when you will start adding some projects to your portfolio you will be sure that your images are clear and look professional 😉 😉

2022-09-01 23:26 UTC, cynthiainga commented on index.html
> +<body>
- [ ] Please when finishing the styling of the desktop version you should make sure that the style of your mobile version is correct and stick as much as possible to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) 😉, kindly fix the styling of your mobile version as well 🙃 🙃

2022-09-02 17:12 UTC, Kamba56 requested changes
Hi @amare1990, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] All linters passed
- [x] Correct use of github flow
- [ ] Descriptive PR summary

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 17:12 UTC, Kamba56 commented on css/styles.css
> +}
- [ ] As requested by the previous reviewer, please kindly remove the margin on the wrapper so that your design will match the template. You can use padding if you want to give space in the container.
- [ ] It is best practice not to use a fixed width so that your page can be responsive in all screen sizes. Kindly change the fixed width to width in %. Try using `width: 100%;`.
## Your design (notice the spaces around)
![1](https://user-images.githubusercontent.com/94551484/188204039-7ee6d8f8-0e46-4d49-96bf-8370ac10c592.png)
## Figma template
![f1](https://user-images.githubusercontent.com/94551484/188203979-dd7705c5-915b-46a3-a38e-7152ca67eeb6.png)

2022-09-02 17:12 UTC, Kamba56 commented on css/styles.css
> +}
- [ ] As requested by the previous reviewers. Please make your about section look like the design template by centering the contents. You can add the padding left and right to push the contents to the center. You can try using `padding: 114px 10%;`.
## Your design
![2](https://user-images.githubusercontent.com/94551484/188204227-e1377072-b441-4749-8009-80fa3f99f190.png)
## Figma template
<img width="864" alt="f2" src="https://user-images.githubusercontent.com/94551484/188204252-a82d8238-5f01-4a4b-abf7-c224b6d283f7.png">

2022-09-02 17:12 UTC, Kamba56 commented on css/styles.css
> +  right: -20px;
- [Optional] Please consider removing this property. (`right: -20px;`) because it creates a margin to the right of your portfolio.

2022-09-02 17:12 UTC, Kamba56 commented on index.html
> +        <img src="/images/contact-form-shapes-mobile.png" alt="Contact Form Shapes" class="contact-form-shapes contact-form-shapes-mobile">
- [Optional] Please note that all images used for decoration purposes should be added as a background image in CSS. Consider moving this image to become a background image to this section in CSS.

2022-09-02 17:40 UTC, amare1990 commented on css/styles.css
> +}
Hi Mr.,
I use Firefox browser and five server from VS code. I do not notice such kind of page for the home page. Probably you may have opened the previous linked I sent for the first or second code review.
Kindly see this please.

2022-09-02 17:46 UTC, amare1990 commented on css/styles.css
> +}
Here, it is the screenshots for the different desktop version screen sizes.
![Screenshot from 2022-09-02 20-40-35](https://user-images.githubusercontent.com/38856938/188209283-07171a23-f8b9-4622-aa0f-7947dbaeadb4.png)
![Screenshot from 2022-09-02 20-40-17](https://user-images.githubusercontent.com/38856938/188209295-3a4a7a35-ed15-41e7-a5da-a8a1040e62a3.png)

2022-09-02 21:13 UTC, zainsadaqat approved these changes
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @amare1990  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 

<img src="https://media2.giphy.com/media/PaSnUZW1EeypulsOwd/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 22:13 UTC, merged