Portfolio: Added mobile menu
amare1990/Portfolio-Amare pull request #2
Opened 2022-09-13 19:30 UTC by amare1990

- Add ..eslintrc.json file.
- Add markup page for the mobile menu.
- Add CSS styles for the mobile menu.
- Add JS for adding dynamics to the webpage.
- Add scroll events for each menu link.
- Modify the homepage of the mobile version to be blurred

2022-09-13 20:38 UTC, vickymarz requested changes
Hi @amare1990 , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 20:38 UTC, vickymarz commented on js/scripts.js
> +});
- [ ] You have really tried implementing the mobile menu functionality 👍🏽, but currently, the function you added to toggle the mobile menu is not working. When I click the hamburger, the mobile menu doesn't display but rather I get an error in the console. Kindly debug the issue and fix it 👍🏽

![image](https://user-images.githubusercontent.com/63473584/190004212-d901bcbd-1e03-457c-b993-dba45fc10021.png)

2022-09-13 20:38 UTC, vickymarz commented on js/scripts.js
> +closeButton.addEventListener('click', mobileMenuDisplay);
- [ ] You have really tried implementing the mobile menu functionality 👍🏽, but currently, the function you added to toggle the mobile menu is not working. When I click the hamburger, the mobile menu doesn't display but rather I get an error in the console. Kindly debug the issue and fix it 👍🏽

![image](https://user-images.githubusercontent.com/63473584/190004212-d901bcbd-1e03-457c-b993-dba45fc10021.png)

2022-09-13 22:35 UTC, FrederickMih requested changes
Hi @amare1990 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- The Hamburger button works as expected :+1: 

 ## Required Changes ♻️

- **Please kindly make sure to include a descriptive README file. I think the previous reviewer forgot to invalidate the PR. We required a descriptive README.md file for each project.**

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-13 22:35 UTC, FrederickMih commented on css/styles.css
> +  backdrop-filter: blur;
- Great job for fixing the hamburger button issue raised by the previous reviewer :+1: 

- [ ] Your design is slightly different from the one in Figma. Kindly check the screenshots below:

| Yours | Figma |
| --- | --- |
| ![Screenshot from 2022-09-13 22-53-07](https://user-images.githubusercontent.com/63087491/190019941-7e441a3b-9ee6-4b01-9c20-827ad03f2d17.png) | ![Screenshot from 2022-09-13 23-00-34](https://user-images.githubusercontent.com/63087491/190019969-1c49971c-537f-4d95-abf8-79ba7ceecb4e.png) |

Let's make sure that the font weight, and size are the same as in Figma. Also, adjust your close icon to position as seen in the original screenshot. Your contact option is hidden by the header text. Let's fix the issues. Also, ensure that there are no console errors.

2022-09-14 17:35 UTC, smunozmo approved these changes
Hi @amare1990, 👋 

## Highlights 👏 

- Excellent job making all the suggested changes! 🎉 
- Mobile menu is working properly, perfect! 😎 
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 17:43 UTC, merged